# Generated by Django 4.1.3 on 2023-05-30 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_alter_order_created_date_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 19, 24, 31, 921630)),
        ),
    ]
