# Generated by Django 4.1.3 on 2023-06-17 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_alter_order_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 17, 11, 52, 44, 48070)),
        ),
    ]
