# Generated by Django 4.1.3 on 2023-06-17 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_alter_order_created_date_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 17, 17, 26, 38, 952749)),
        ),
    ]
