# Generated by Django 4.1.3 on 2023-06-18 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_alter_order_created_date_alter_order_user'),
        ('ecommerce', '0019_alter_order_created_date'),
        ('ecommerce', '0022_alter_order_created_date_alter_product_category'),
    ]

    operations = [
    ]
