POST http://localhost:8000/order/
Content-Type: application/json
Authorization: Token 7f5d1a40c5873ecac39de486387629f1546f9776

{
    "user": "artur",
    "adress": "test", 
    "postal_code": "test",
    "city": "test",
    "created_date": "2023-06-17",
    "paid": "False" 
}

###
# Get will return all orders for one user (depends on token)
GET http://localhost:8000/order/
Content-Type: application/json
Authorization: Token 7f5d1a40c5873ecac39de486387629f1546f9776

